version: "3.7"
services:
  ui:
    build: .
    image: raymonteam/raymon_frontend:0.0.37
    ports:
      - "8080:80"
    environment:
      API_URL: <to replace>

  api:
    image: raymonteam/raymon_api:0.0.38
    ports:
      - 8000:5000
    environment:
      PYTHONUNBUFFERED: 1 # Force print flushes
      SECRET_PATH: /run/secrets
      RAYMONDB_HOST: db
      RAYMONDB_PORT: 5432
      RAYMONDB_DB: raymon
      RAYMONDB_USER: postgres
      RAYMONDB_PASSWORD_SECRET: raymondb-password
      QUEUE_OUTPUT: "true"
      KAFKA_HOST: "kafka"
      KAFKA_PORT: 9092
      KAFKA_MAPPER_TOPIC: map-req-topic
      # MGMT config
      RAYMON_MGMT_URL: https://mgmt.raymon.cloud
      RAYMON_MGMT_API_CLIENT_ID: <to replace>
      RAYMON_MGMT_API_CLIENT_SECRET: raymon-mgmt-api-secret
      RAYMON_MGMT_API_AUDIENCE: raymon-mgmt-api
      RAYMON_API_AUDIENCE: raymon-backend-api
      RAYMON_AUTH0_URL: https://raymon.eu.auth0.com
    secrets:
      - raymondb-password
      - raymon-mgmt-api-secret
    depends_on:
      - db

  db:
    image: raymonteam/raymon_db:0.0.38
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: raymon
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD_FILE: /run/secrets/raymondb-password
    secrets:
      - raymondb-password
    volumes:
      - dbdata:/var/lib/postgresql/data/

  zookeeper:
    image: "docker.io/bitnami/zookeeper:3-debian-10"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: "docker.io/bitnami/kafka:2-debian-10"
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,LOCALEXTERNAL:PLAINTEXT,DOCKEREXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,LOCALEXTERNAL://:9093,DOCKEREXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,LOCALEXTERNAL://localhost:9093,DOCKEREXTERNAL://host.docker.internal:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_MESSAGE_MAX_BYTES=15000000
      - KAFKA_CFG_REPLICA_FETCH_MAX_BYTES=15000000
    depends_on:
      - zookeeper

  mapper:
    image: raymonteam/raymon_mapworker:0.0.38
    environment:
      PYTHONUNBUFFERED: 1 # Force print flushes
      SECRET_PATH: /run/secrets
      RAYMONDB_HOST: db
      RAYMONDB_PORT: 5432
      RAYMONDB_DB: raymon
      RAYMONDB_USER: postgres
      RAYMONDB_PASSWORD_SECRET: raymondb-password
      KAFKA_HOST: "kafka"
      KAFKA_PORT: 9092
      KAFKA_MAPPER_TOPIC: map-req-topic
    secrets:
      - raymondb-password
    depends_on:
      - kafka
      - db

  reducer:
    image: raymonteam/raymon_reducer:0.0.38
    environment:
      PYTHONUNBUFFERED: 1 # Force print flushes
      SECRET_PATH: /run/secrets
      RAYMONDB_HOST: db
      RAYMONDB_PORT: 5432
      RAYMONDB_DB: raymon
      RAYMONDB_USER: postgres
      RAYMONDB_PASSWORD_SECRET: raymondb-password
      KAFKA_HOST: "kafka"
      KAFKA_PORT: 9092
      KAFKA_REDUCE_TOPIC: reduce-req-topic
    secrets:
      - raymondb-password
    depends_on:
      - kafka
      - db

  triggergen:
    image: raymonteam/raymon-triggergen:0.0.38
    environment:
      PYTHONUNBUFFERED: 1 # Force print flushes
      SECRET_PATH: /run/secrets
      RAYMONDB_HOST: db
      RAYMONDB_PORT: 5432
      RAYMONDB_DB: raymon
      RAYMONDB_USER: postgres
      RAYMONDB_PASSWORD_SECRET: raymondb-password
      KAFKA_HOST: "kafka"
      KAFKA_PORT: 9092
      KAFKA_REDUCE_TOPIC: reduce-req-topic
    secrets:
      - raymondb-password
    depends_on:
      - kafka
      - db

volumes:
  dbdata:

secrets:
  raymondb-password:
    external: true
  raymon-mgmt-api-secret:
    external: true
