apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    # For GCP
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: raymon-staging-ip
    networking.gke.io/managed-certificates: raymon-certificate
  labels:
    app: raymon-backend
  name: raymon-api-ingress
spec:
  rules:
    - host: api.aws.raymon.app
      http:
        paths:
          - backend:
              serviceName: raymon-api
              servicePort: 5000
            path: /v0/*
    - host: ui.aws.raymon.app
      http:
        paths:
          - backend:
              serviceName: raymon-ui
              servicePort: 80
            path: /*

---
apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: raymon-certificate
spec:
  domains:
    # Replace with your domain(s)
    - ui.raymon.ai
    - api.raymon.ai
